#!/usr/bin/env python

import os
import subprocess
from charmhelpers import fetch
from charmhelpers.core import hookenv
from cloudfoundry.path import path

hookenv.juju_status('installing')
fetch.apt_install(fetch.filter_installed_packages(['juju-deployer', 'nginx']))
os.unlink('/etc/nginx/sites-enabled/default')
subprocess.check_call([
    'ssh-keygen',
    '-f', path(hookenv.charm_dir()) / 'orchestrator-key',
    '-N', ''])
